### ISSUE TITLE
Pay with Credit Card Button CSS Problem..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#1030]
We have logic in place to change the "Proceed to Checkout" button to say "Pay with Credit Card" if PayPal Pro and Express are the only gateways enabled.

On my own site it's setup this way, but for some reason the "Pay with Credit Card" button styling is messed up.  It looks like when it first loads, but when I hover over it my theme CSS seems to get lost and the button loses proper styling.

Need to see if we're doing something that's causing this..??

**Comment by angelleye** [comment]
My Add to Cart button is doing the same thing.  https://www.angelleye.com/product/paypal-woocommerce-multi-account-management/

Not sure if it's related to something about the smart buttons..??

**Comment by kcppdevelopers** [comment]
@angelleye This issue is not related to our plugin. I have checked and found that it's Divi theme button hover CSS style effect.

Also one more thing I found on checkout page "Pay with Credit Card" button CSS issue is related to 

view-source:https://www.angelleye.com/wp-content/themes/Divi_Child/style.css?ver=3.0.106

Please remove below CSS code:

`.woocommerce-cart .wc-proceed-to-checkout {
    width:250px;
    float:right;
}`
