### ISSUE TITLE
Duplicated order creation

### ISSUE THREAD

**Issue by 13turtles** [angelleye/paypal-woocommerce#1129]
## Problem:
In case the WooCommerce Shop DB is under a lot of stress and only answering beyond the 1 min threshold - and because an order is created only after payment - this is creating duplicated orders for the same payment. This is again leading to customer confusion as well as a lot of work for customer service

Of course we look into making the WC DB as resilient as possible, still this issue of massive duplicated orders is causing us to go back to the "standard" paypal WC payment method. This is neither ideal for the statistics, nor in customer experience. 

## possible solutions (we are open of course to any other):
* check on creation of an order if there is already another one for this payment 
* in times of only slowly answering systems possibility to queue the requests for later 

Thanks and let us know if you do need any more info, 
Anna-Barbara @ Invinciblebrand

**Comment by iMansoorAliKhan** [comment]
Hi @Anna-Barbara,

Thanks for your honest and detailed feedback, although we are not seeing that on our demo site nor we are able to reproduce that , also we dont have any other reports of this sort of issue. Which is making be a bit worried at this stage because we need to be able to reproduce that problem so that we know what is happening and if there are any adjustments we need to make then we will be happy to do that.

Do you have a video recording of orders being duplicate while you are placing it? Can you enlist steps so that i can try the same and see if I am able to reproduce the same error?

Thanks!
Oliver

**Comment by angelleye** [comment]
Moved to Jira:  https://angelleye.atlassian.net/browse/PFW-133
