### ISSUE TITLE
Tokenized Payments Not Working

### ISSUE THREAD

**Issue by marpstar** [angelleye/paypal-woocommerce#1281]
I recently filed issue #1264, where Braintree payments were not sending the Cardholder Name to Braintree.  Since upgrading we've found that the Cardholder Name is now present, but our payments are no longer being tokenized.  We would like BOTH.  

I mentioned in the previous issue that these things seemed to be mutually exclusive. I believe there are still issues here.

Please advise.

**Comment by iMansoorAliKhan** [comment]
@marpstar I apologies for the inconvenience and Appreciate you bringing this to our attention. I have got this added to our backlog and will get this fixed in our upcoming update.

Thanks!

**Comment by iMansoorAliKhan** [comment]
REF: **PFW-372**

**Comment by marpstar** [comment]
@iMansoorAliKhan do you have any ETA on this? If I grab the latest code from GitHub, is this potentially fixed?

**Comment by iMansoorAliKhan** [comment]
Hi @marpstar Thanks writing us here. We this issue is resolved and will be included in our 1.5.8 update which is going to be released soon. If you like to try that early then please download our release branch and update manually.

> **Additionally, as you may be aware that we have moved our plugins to self hosted servers so we will be delivering our updates from hosted servers. To get those updates please install angelleye Updater and you will start getting updates like before.**

We would love to know what you think of our product and customer support. If you have a moment to [ **Leave A review** ](https://www.angelleye.com/product/woocommerce-paypal-plugin/#tab-reviews) it would be greatly appreciated.

Thanks!
