### ISSUE TITLE
Switching subscription to Paypal causes error

### ISSUE THREAD

**Issue by njbarrett** [angelleye/paypal-woocommerce#1304]
Hi there,
While using this plugin with Woocommerce Subscriptions, I notice that when attempting to switch an existing subscription's payment method to Paypal, the following error is produced:

10525 - This transaction cannot be processed. The amount to be charged is zero.

The subscription payment method changes successfully, but the next time the renewal is due it fails because no billing agreement was setup.

Here are my version numbers:

WooCommerce 3.5.7
WooCommerce Subscriptions 2.5.3 
Paypal for Woocommerce 1.5.7

**Comment by iMansoorAliKhan** [comment]
Hi @njbarrett 

Thanks for writing us here.

Can you tell me which Payment method you are using from our plugin so that we know whats causing trouble and we can possible try to reproduce this on our test site?

Please check and let me know.
Thanks!
Oliver


*Oliver Green*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by njbarrett** [comment]
@iMansoorAliKhan It is the Paypal Express Checkout gateway, thank you

**Comment by iMansoorAliKhan** [comment]
@njbarrett We are looking into this and will get back to you as quickly as we can.
Thanks!

**Comment by angelleye** [comment]
@iMansoorAliKhan  Did you get a ticket created for this in Jira?

**Comment by iMansoorAliKhan** [comment]
@angelleye  Yeah Just added this to backlog.

**Comment by iMansoorAliKhan** [comment]
https://angelleye.atlassian.net/browse/PFW-401

**Comment by drewangell** [comment]
This should be resolved in the latest version of our plugin.
