### ISSUE TITLE
Not listed as payment option; separate button on cart page

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1400]
The new smart PayPal button is listed on the cart page, but also the "Buy now" button and the list of payment options is empty with a message that there are no payment options.
Either PayPal is added to the payment options list or the whole list and "Buy now" button removed from the cart page.

**Comment by iMansoorAliKhan** [comment]
HI @strarsis ,

Thanks for writing us here but I am confused by you question. Let me restate it based on what I understood.
- You have smart button active on cartpage along with proceed to checkout option???
- On checkout page in regular gateway list you dont see any of the payment options

Is that correct?

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by strarsis** [comment]
@iMansoorAliKhan: I meant the checkout page, sorry for the confusion.
Yes, currently there is the PayPal smart button _and_ the regular "Buy now" button both on the _checkout_ page. And also an empty list of payment methods with a message that there are no payment methods currently available.

**Comment by iMansoorAliKhan** [comment]
@strarsis Can you share a screenshot please.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by strarsis** [comment]
Empty payment methods list (with message):
![empty-payment-methods-list](https://user-images.githubusercontent.com/9271436/70378633-fb110300-1922-11ea-80d0-c37bbd6283b2.png)

Both buttons are shown, smart PayPal button and "Buy now" button:
![both-buttons](https://user-images.githubusercontent.com/9271436/70378634-fc423000-1922-11ea-931e-274f05ae50e9.png)

**Comment by iMansoorAliKhan** [comment]
Thats interesting, Can you provide your site URL please? Because our plugin normally not do that so I am not sure if that button is from our plugin or woo paypal checkout?
Please share the site so that I can take a look.

Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by strarsis** [comment]
@iMansoorAliKhan: The error message in English: 

> Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements.

**Comment by strarsis** [comment]
`class-wc-gateway-ppec-checkout-handler.php`:549:
```php
// If using PayPal standard (this is admin choice) we don't need to also show PayPal EC on checkout.} elseif ( is_checkout() && ( isset( $gateways['paypal'] ) || 'no' === wc_gateway_ppec()->settings->mark_enabled ) ) {
	unset( $gateways['ppec_paypal'] );
}
````
PayPal Standard is disabled in Payments options page, also `$gateways['paypal']` is not set.
The OR part branch of this `elseif` condition, `'no' === wc_gateway_ppec()->settings->mark_enabled` is fullfilled, because `wc_gateway_ppec()->settings->mark_enabled` is `false`.

`mark_enabled` is nowhere set in your plugin, but apparently it is needed for being used as a payment method in the WooCommerce checkout page when in an "active session" (`if ( $this->has_active_session() ) {`).

**Comment by iMansoorAliKhan** [comment]
For this I don't think we need to look at the code level. What I am confused is that why the button shows when the error message says that there is no Payment option available. This is why I wanted to review your site because I think you are using Woocommerce checkout plugin and not our PayPal for woocommerce. 

If you will install our plugin then you will not experience anything like this. 

Please check that and let me know if there will be any concerns.
Thanks!
Mansoor


*Mansoor Khan*
Angell EYE Customer Support Specialist
[www.angelleye.com](https://www.angelleye.com) | [Join Our Newsletter](https://www.angelleye.com/newsletter-signup/?utm_source=email&utm_medium=signature&utm_campaign=email_signature)
[Subscribe to Our YouTube Channel](https://www.youtube.com/user/angelleyeconsulting) | [Like Our Facebook Page](https://facebook.com/angelleyeconsulting/)

**Comment by varried** [comment]
I am experiencing the same problem. Enabled PayPal express checkout but it is not showing in my checkout page as a payment method.  
![image](https://user-images.githubusercontent.com/48599177/73128190-99a61000-4006-11ea-8844-d15f37367e1f.png)
