### ISSUE TITLE
Review page disabled? No errors displaying.

### ISSUE THREAD

**Issue by a4anes** [angelleye/paypal-woocommerce#1582]
After customers return from PayPal express checkout, review page is disabled? They can't make any changes to the shipping address. All fields are disabled and no errors showing. Phone number is required in our checkout and if paypal does not return with a phone number on the review page, customer can't add the phone number because it is disabled and can't complete the order. 

Getting these in the error log. But it should show up error. Customers are calling us that checkout is not working. 

PayPal DoExpressCheckoutPayment API call failed
Error Code: 10486
Error Severity Code: Error
Short Error Message: This transaction couldn’t be completed.
Long Error Message: This transaction couldn’t be completed. Please redirect your customer to PayPal.

![Screenshot - 2021-10-04T173127 642](https://user-images.githubusercontent.com/1378209/135851805-97c2abda-cbd5-400d-861d-e846e1fa66bf.png)

**Comment by drewangell** [comment]
I'm sorry I never got back to here.  We are using Jira and I wasn't seeing the notices about GitHub issues.  Sorry about that!

If you still need help with this please create a ticket at www.angelleye.com/support and we'll get you taken care of.

**Comment by drewangell** [comment]
Oh, I can tell you quickly that 10486 means the funding method chosen by the payer during checkout was not valid for payment.  It would send the user back to PayPal to try and choose another option.  You get that notice because it is indeed an API payment failure, but it's not an unexpected one, per se.  It's just a like a declined card, for example.
