### ISSUE TITLE
PayPal Commerce Upgrade notification

### ISSUE THREAD

**Issue by strarsis** [angelleye/paypal-woocommerce#1943]
After updating to latest plugin version, a non-dismissible upgrade notification is displayed that one should upgrade to PayPal Commerce. Is this a successor to PayPal ExpressCheckout? Or a different plugin? And can I just re-use the existing API keys or is a new authorization required?

**Comment by devchristina2** [comment]
Hi @strarsis, 

Apologies for the delay in our response. Due to the age of this issue, I'm going to close it as completed. If you're still facing issues, you can submit a ticket with our team using our updated support process [here](https://angelleye.atlassian.net/servicedesk/customer/portals).

Thanks, Christina.
