### ISSUE TITLE
WordPress Vulnerability..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#202]
Need to review this problem and make sure our plugin isn't affected. If it is, we need to get it updated.

https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/

**Comment by siliconforks** [comment]
It looks like there's a number of other occurrences of add_query_arg besides those addressed in the fix, e.g., in paypal-for-woocommerce.php it is used several times for the admin section.  Should those be modified to use esc_url too?

**Comment by angelleye** [comment]
@siliconforks I'll check it out.

@jigneshkailam What do you say about this?

**Comment by angelleye** [comment]
@siliconforks It seems that the places where add_query_arg() is used in paypal-for-woocommerce.php are places where static data is passed in as opposed to dynamic data.  As such, esc_url() is not necessary here.

**Comment by siliconforks** [comment]
The data passed in as parameters is static, but add_query_arg uses the superglobal variable $_SERVER['REQUEST_URI'].  See:

https://make.wordpress.org/plugins/2015/04/20/fixing-add_query_arg-and-remove_query_arg-usage/

The problem is that $_SERVER['REQUEST_URI'] is just the current URL, which can potentially be manipulated by an attacker.

**Comment by angelleye** [comment]
Thanks for the details.  We'll get it handled.

**Comment by angelleye** [comment]
@jigneshkailam Looks like we should do something like this:  http://smartik.ws/2015/04/safe-add_query_arg-and-remove_query_arg/
