### ISSUE TITLE
express checkout cart button

### ISSUE THREAD

**Issue by seesoe** [angelleye/paypal-woocommerce#206]
hello, i am trying to use this plugin is express checkout button on the cart page to replace the proceed to checkout page. is there a way this can hook and remove the proceed to checkout link if the paypal button is on the cart page?

**Comment by angelleye** [comment]
It used to do that, but the 2.3 update for WooCommerce made some changes to the way they handle the checkout button, so it broke our logic that would hide that for you, unfortunately.

We've been a little bit behind on updates because I've been so swamped with work, but I just this week placed a new (quality) developer on this project full time.  As such, we'll start seeing much more frequent updates and we'll be keeping up with WC a lot better.

In the mean-time, you should be able to hide the WC checkout button from the CSS in your theme.  I would recommend you do that from a child theme.

**Comment by seesoe** [comment]
thank you for the reply, i look forward in this being fixed and the project moving forward! thanks again!

**Comment by angelleye** [comment]
This has been resolved in our dev branch, so I'm going to close this ticket.  We're still wrapping up a few other issues in our 1.1.6.3 milestone, but it will be ready soon!
