### ISSUE TITLE
Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper

### ISSUE THREAD

**Issue by kevin25** [angelleye/paypal-woocommerce#2062]
I still got tone of this error with php 8.2.2

PHP message: PHP Deprecated:  Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$cart_button_layout is deprecated in paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php on line 156"

paypal-woocommerce Version: 4.5.7

**Comment by kevin25** [comment]
Deprecated | Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$cart_button_size is deprecated | +wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php:158 | 1 | Plugin: paypal-for-woocommerce
-- | -- | -- | -- | --
Deprecated | Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$cart_button_height is deprecated | +wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php:159 | 1 | Plugin: paypal-for-woocommerce
Deprecated | Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$cart_button_label is deprecated | +wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php:160 | 1 | Plugin: paypal-for-woocommerce
Deprecated | Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$cart_disallowed_funding_methods is deprecated | +wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php:161 | 1 | Plugin: paypal-for-woocommerce
Deprecated | Creation of dynamic property Angelleye_PayPal_Express_Checkout_Helper::$is_order_completed is deprecated | +wp-content/plugins/paypal-for-woocommerce/angelleye-includes/express-checkout/class-wc-gateway-paypal-express-helper-angelleye-v2.php:319

**Comment by drewangell** [comment]
@kevin25 I'm sorry you did not get a reply here sooner.  Our Jira system is typically where we do our help desk, but I never disabled issues here.  I didn't mean to leave you hanging!  We'll get that resolved.

Anyway, I can see that you are using a slightly outdated version of our plugin, so it would be good to get updated.

More importantly, though, the error you're referencing is related to "Classic Express Checkout" which is no longer supported.  

PayPal now provides the new "Complete Payments" platform, which our plugin now supports.

Please make sure you get updated to the latest version of our plugin (v4.5.19) and you should see a notice about upgrading from Classic to Complete Payments.

You can follow the upgrade path from that notice to connect your PayPal account to the new system, and it will take care of disabling the old stuff.

It will also migrate any subscription profiles from the old stuff to the new if you happen to be running those.  Again, though, just make sure you get updated to the latest version before you do that, so that you have all the latest changes related to migration.

I'm going to go ahead and close this ticket since we aren't supporting classic PayPal anymore.  Feel free to submit a ticket here, though, if you have more questions or concerns related to migrating:  https://angelleye.com/support

Thanks!
