### ISSUE TITLE
Express Checkout - Product Details EC Button Adjustment

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#209]
Right now we're doing some funky jQuery stuff with the WC Add to Cart button in order to get our PayPal EC button to show up directly to the right of it.  This is causing lots of issues with styles on themes, especially since the WC 2.3 update.

Need to make follow more of a standard.  Other developers have complained that they cant' use the "after_add_to_cart" hooks properly because of what it's doing.

Might want to look at how kcwebmedia did it in our Offers for WooCommerce plugin.  We have an option to display the offer directly to the right of the Add to Cart button and it was done more clean (I think.)

**Comment by nishitlangaliya** [comment]
Hi Andrew,

-> I read the comments and see the code . for display checkout button right side to add to cart button on product detail page.

-> We are using 'woocommerce_after_add_to_cart_button' hook to display that and we do not have applied special css to display the checkout button on the right side to add to cart button. 

-> Its a hook that works that, I notice that any function written on Woocommerce_after_add_to_cart_button' hook  that things will come next to add to cart button on product detail page. only if the space is available to right side to "Add to Cart" Button. other wise it will go down to add to cart button.

-> In woo.angelleye.com there is storefront theme is active. and its product detail page template has a enough space to left side div. to adjust the checkout button right to add to cart button. But If you activate twenty twele theme or other default theme you can see that checkout button comes down.

-> I see the code of offers-for-woocommerce and they have used the same woocommerce_after_add_to_cart_button' hook to display the make an offer button to right side on shop page. but if you go to product detail page it will display down to add to cart button. 

-> So here my thinking is other developer should not have an issue by using 'woocommerce_after_add_to_cart_button' hook. because that hook will just simply add
content below the add to cart button and We can see that we have both offers-for-woocommerce and paypal for woocommerce plugin activated and both have used the woocommerce_after_add_to_cart_button' hook but there is no conflict . 

-> so please let me know your suggestions and thoughts for the same. and if any instruction regarding it.
