### ISSUE TITLE
Customer name as "guest" vs. their real name.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#227]
In #174 and #175 we added options to include NOSHIPPING in the PayPal request.

In #215 we adjusted things to ensure that when the WC checkout page is used, that's the data we use for the PayPal requests, so if NOSHIPPING is set we should still be sending a billing address there, and then that name should be used instead of "Guest" on the order.

When an Express button is used from the product or cart page, though, then we don't have any name, and if they have NOSHIPPING set, we don't get a shipping address back from PayPal either.  This results in the order getting created in WooCommerce with "Guest" as the name.  #225 has some details about this.

The PayPal GetExpressCheckoutDetails response should have a "firstname" and "lastname" separate from the shipping details that would typically be returned, so we need to make sure to use that for the order instead of letting it use "Guest".

**Comment by nishitlangaliya** [comment]
![screenshot-ipnsupport dev2 in 2015-08-05 14-50-14](https://cloud.githubusercontent.com/assets/11435772/9082506/284c2d82-3b82-11e5-8d48-631681635b8f.png)

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have test the case on cart page and product page by logged in and logged out user . for reproduce the case. but I did not found name as guest there in order. accordingly me it was working as expected.

I have prepared video for what I test below is URL. please see when you get a chance.

URL: http://www.screencast.com/t/LnPh1uc8JX0

I also see the paypal_express_checkout () function code we are already getting  using "  $split_name = $parser->split_full_name($result['SHIPTONAME']);" for getting the name of user from paypal result. 

Let me know your thoughts for the same. and also if still user has an Issue can we get the settings screenshot of user so that we might be able to reproduce the case.

**Comment by kcppdevelopers** [comment]
I have checked and found that we have already resolved this issue in previous release.

**Comment by angelleye** [comment]
Are you sure you tested this exact scenario?  So even when NOSHIPPING is enabled in the API request then we're getting a name saved with the order instead of guest?

**Comment by kcppdevelopers** [comment]
Yes, I have tested this exact scenario. it's working fine.
