### ISSUE TITLE
Express Checkout - Cart Button(s)

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#252]
Something about the way we're handling our Express Checkout buttons on the cart page is causing a conflict with many themes.

In fact, in the video you provided for #245 we can see it.  When you get to the cart we see this...

![image](https://cloud.githubusercontent.com/assets/629241/8809448/550e1f90-2fae-11e5-9dd3-872b4ff6dd15.png)

You'll notice that the Express Checkout button is actually hidden under the Proceed to Checkout button, which is getting pulled too far to the right because our buttons are inside that div.  We can just barely see the messaging at the bottom of the EC button here.  All we can really see is the PayPal Credit button, and people have that disabled quite a bit so then they can't see anything.

What we should have here is something more like this, where the Proceed to Checkout button is left alone, and our buttons are in their own div.

![image](https://cloud.githubusercontent.com/assets/629241/8809573/2e36fef4-2faf-11e5-97c0-8c14c2ca79f0.png)

**Comment by nishitlangaliya** [comment]
Hi Andrew ,

I am done with this issue and pushed to 'Issue-252' branch for a review. To make compatible with most  of all the themes I had moved cart total div to left side. because there is only two hook is there "woocommerce_proceed_to_checkout"  and "woocommerce_after_cart_totals".

We have to use woocommerce_after_cart_totals hook and using this hook it will display our image below proceed to checkout button . and we need to show it at left side . if we manage that using margin and other css than it would not display at perfect position in all theme. if the cart total div is on left side it will work perfect for all themes. so that is why i have set its style to left side. so please check for the same when you get a chance and let me know your thoughts for the same.
