### ISSUE TITLE
Conflict with Woocommerce PrePurchase

### ISSUE THREAD

**Issue by ColonelMillerSG21** [angelleye/paypal-woocommerce#258]
I bought this plugin to over prepurchase on my store: http://codecanyon.net/item/woocommerce-prepurchase/8975848

The issue is that they do not coexist with each other very well. When i activate the prepurchase plugin, paypal express buttons on product detail pages will not redirect me to paypal instead they will just put the product into the cart. This is my Shop: http://terrylynnmelody.com/shop/
Another issue was that the paypal express buttons wouldn't wanna show up on some product detail pages, even though the settings where exactly the same in all products, only with different text and mp3 files. So i used !important to force the page to show the button. This issue is not related to the other plugin though and i do not have any cache plugins installed.

**Comment by angelleye** [comment]
@ColonelMillerSG21 We are currently working to finalize the 1.1.6.3.5 update so that we can get it released.  We also have all of the issues for 1.2 already planned and pretty much done, so that will be coming shortly after.

I will add this particular issue to our 1.2.1 milestone.  We will research it at that time and resolve any potential problems in our plugin causing these issues that we can find.

So we won't be able to get to it immediately, but it shouldn't be long.  If you'd like us to bump this up on the priority list you can [submit an order for premium support](https://www.angelleye.com/product/premium-support/).

**Comment by kcppdevelopers** [comment]
@angelleye I have checked aboved issue with Woocommerce PrePurchase plugin, for me it's working fine.

I have checked this on http://terrylynnmelody.com/shop/ website and found that product details page not working dua to jQuery error of https://wordpress.org/plugins/woodiscuz-woocommerce-comments/ plugin. 

Please see the screnshot for more information: http://screencast.com/t/SsazqwZzvwuN

**Comment by angelleye** [comment]
@ColonelMillerSG21 Did you see the info that @kcppdevelopers provided here for you about the jQuery error causing your issue?
