### ISSUE TITLE
WooCommerce 2.4 Updates

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#263]
Need to look through WC 2.4 update changelog and see if there is anything we need to adjust in our plugin.

For example, I see that they have "Created a template file for the Proceed to Checkout button."  I know we're doing some things with that button based on certain logic.  Not sure if we need to make any adjustments now that there is a template file for it..??

Their full list of updates is available on GitHub:  https://github.com/woothemes/woocommerce/issues?q=is%3Aissue+milestone%3A%222.4+Helpful+Hedgehog%22+is%3Aclosed

**Comment by angelleye** [comment]
Here is a good resource for reviewing everything that has changed:  https://woocommerce.wordpress.com/2015/07/13/woocommerce-2-4-beta-testing-begins/

**Comment by nishitlangaliya** [comment]
Hi Andrew,

I have seen the changelog and links you provided for 2.4 version. The new thing regarding 
"Created a template file for the Proceed to Checkout button" i see that in new version they have provided template file for 'Proceed to Checkout' button at 'woocommerce/templates/cart/proceed-to-checkout-button.php'  in that they have simply provided html of proceed to checkout button so that user can directly override text and html of button.

Other stuffs I read . as per my thinking that should not be affect our plugin because . while new version came we had run into issue. and that we have sorted out. and also i was working with latest version.

Please let me know if any thoughts for the same.

**Comment by angelleye** [comment]
Ok, thank you for reviewing the information.  We'll consider it closed.

**Comment by angelleye** [comment]
Everything seems good!
