### ISSUE TITLE
Refunds are not working correctly.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#267]
This may have something to do with the WC 2.4 update.  I'm not sure.

I ran an order with Express Checkout for $90.27.  I then ran a partial refund through WooCommerce for 50.00.

I can see that our PayPal request was accurate and did refund $50.00...

        [REQUESTDATA] => Array
        (
            [USER] => sandbo_1215254764_biz_api1.angelleye.com
            [PWD] => 1215254774
            [VERSION] => 112.0
            [BUTTONSOURCE] => AngellEYE_SP_WooCommerce
            [SIGNATURE] => AiKZhEEPLJjSIccz.2M.tbyW5YFwAb6E3l6my.pY9br1z2qxKx96W18v
            [METHOD] => RefundTransaction
            [TRANSACTIONID] => 6B332538PL464154S
            [REFUNDTYPE] => Partial
            [AMT] => 50.00
            [CURRENCYCODE] => USD
        )

However, in WooCommerce the order got updated as if the entire amount was refunded...

![image](https://cloud.githubusercontent.com/assets/629241/9245945/b1aac732-416d-11e5-9f86-82aabec47e5d.png)

**Comment by nishitlangaliya** [comment]
Done, pushed to 'Issue-267' branch and merged to 1.1.6.3.5 for a review.

I found that in 'process_refund()' function '$order->update_status('refunded');' line was causing a issue due to this line it was doing all amount refunded in woocommerce admin panel. but in paypal api call was working as expected. 

So I have commented this line now. and it worked as expected in admin panel and in paypal as well. please review when you get a chance and let me know your thoughts.

**Comment by angelleye** [comment]
Yes, the refund worked as expected this time.

**Comment by angelleye** [comment]
Well, I take that back.  It's working in Express Checkout, but I just tested with DoDirectPayment and it did not work correctly.  It's doing exactly what EC was doing before you fixed it.  

I'm about to check PayFlow to see if it has the same problem.

**Comment by angelleye** [comment]
yes, PayFlow did the same thing, too.  Need to get this resolved in both of those.

**Comment by nishitlangaliya** [comment]
I have applied the same changes as I did with EC in DDP and payflow in DDP i have successfully tested but for payflow i could not test after the changes I did because In my manager.paypal.account while making transaction as accept below error comes as it goes in fraud transaction

Error: There was an error communicating with the Fraud Protection Service. Please contact Customer Service if this error continues to occur.

so would you please check for payflow and let me know is refund issue sorted or not. I am sure for EC and DDP

Code pushed to 'Issue-267A' and merged to 1.1.6.3.5.

**Comment by angelleye** [comment]
We still have problems here, and I think this is also happening with Express Checkout.  I just didn't notice it before.

Whatever you did caused the refund amount to reflect correctly in WooCommerce.  The problem is that now the order status is not updating to Refunded, but instead is getting left with the current status (Processing).  

Also, the refund transaction ID and notes are not getting added into the WooCommerce order notes the way they used to.

**Comment by angelleye** [comment]
I just double checked the last one I did and it looks like the Refund Transaction ID did make it into the WC order notes, so I was wrong about that.

The status is not updating, though.  Maybe it only does that on a full refund..??  I'm about to test that.

**Comment by nishitlangaliya** [comment]
Done, pushed to 'Issue-267B' and merged to 1.1.6.3.5 for a review.

**Comment by angelleye** [comment]
I've been discussing this with Woo trying to get clarification on how this should be handled (https://github.com/woothemes/woocommerce/issues/8028).  Waiting on an answer there at this point.

What we've done here is sort of "as good as it gets" but it's not perfect, as I explained in the referenced link above.  I feel like something changed in WC 2.4 that is causing this to be quirky.

For now we'll consider it a closed matter and possibly deal with it again later if Woo confirms they need to adjust something.
