### ISSUE TITLE
WooCommerce Hear About Us Compatibility

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#392]
Request from vutang @ paypal.

User is attempting to use this plugin in conjunction with ours, but the setting is not showing up on the order when checkout is complete.  It works with PayPal Standard, but not our Express Checkout.

![image](https://cloud.githubusercontent.com/assets/629241/12400476/de9ed5ea-bde5-11e5-9132-1059d30b6bef.png)

I think we probably need to hook into our review page for Express Checkout to add the "hear about us" selection, and then make sure it gets saved on the order as it typically would with the WC checkout page.

Also need to make sure it's working with Payments Pro (DDP and PayFlow) but since those use the WC checkout page I think they may not be an issue. Still need to test it.

**Comment by kcppdevelopers** [comment]
I am unable to display "hear about us" filed into the our review page for Express Checkout, because  "hear about us" is part of check page. Also there are few other problem like WooCommerce Hear About Us plugin used global post variable and $checkout object. In our plugin it's not available because user is come from PayPal.   

Let me know your suggestion for the same.

**Comment by angelleye** [comment]
Link to Hear About Us plugin:  https://wordpress.org/plugins/woocommerce-hear-about-us/

**Comment by angelleye** [comment]
What we wound up doing here is making this compatible with any plugin.

Any plugin that adds custom fields to the checkout page, those same fields are now added to our Express Checkout review page.

This only happens, though, if the WooCommerce checkout page was skipped.
