### ISSUE TITLE
Hook to hide unused gateways.

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#506]
https://wordpress.org/support/topic/disable-unused-payment-gateways?replies=1#post-8624481

**Comment by kcppdevelopers** [comment]
I have test sample code, for me it working fine for default payment gateways that are not used. if user want to hide any other third party payment gateways like our plugin then user need used high priority in the filter.

Just need to used 1001 instead of 20, please see the below example:

`add_filter( 'woocommerce_payment_gateways', 'custom_remove_unused_payment_gateways', 1001, 1 );`

Thanks!
