### ISSUE TITLE
What happens if customer cancels payment process in paypal?

### ISSUE THREAD

**Issue by florianbepunkt** [angelleye/paypal-woocommerce#567]
Sorry if this is a rather stupid question: But what happens if customer orders, is taken to paypal and cancels or abandons they payment process there? I got lots of orders with "pending" status and no paypal payment received.

Inidicated this an IPN issue? Or is this default WooCommerce behaviour? I wonder why an order is created if the payment process failed. Any way to change this behaviour, so that an order is only created when paypal payment was successful?

Thanks,
Florian

**Comment by angelleye** [comment]
Are you using Express Checkout with our plugin?

If they cancel they would be returned to the Cancel URL you have configured in the plugin settings.  The order wouldn't have been created at that point yet unless you're still using the WC checkout with Express Checkout.  Is that the case?

**Comment by florianbepunkt** [comment]
No, not using Express checout. Sorry, my question was more general… what is the concept / basic logic behind the WC checkout when it comes to paypal? Are orders only created when the payment was successful? At least that's how it is supposed to work as far as I understodd.

Because for me some orders are fine (they have status "processed" and I can see the payment in Paypal backend), but some are left pending and there is no payment in PayPal backend.

**Comment by angelleye** [comment]
This is really not the best place for general questions.  This repo is specific to our PayPal for WooCommerce plugin.  

If you are using the built in PayPal Standard that comes with WooCommerce then it will create the order when checkout is submitted and leave it as pending.  Then when the payment is completed an IPN would trigger which updates the order to Completed.  If the buyer doesn't complete payment it would be left as pending in your system.  This would give you the option to follow up with that person and try to complete the sale.

I would recommend you use our plugin with Express Checkout instead of PayPal Standard.  There are [plenty of benefits](https://youtu.be/VhQT8rX7uwE) to it.
