### ISSUE TITLE
Payment error: 52-Insufficient permissions to perform transaction

### ISSUE THREAD

**Issue by muddassirh** [angelleye/paypal-woocommerce#580]
Hello 

I'm getting error "Payment error: 52-Insufficient permissions to perform transaction" in sanbox mode. I'm using PayPal PayFlow as payment gateway. Would you please help?

**Comment by angelleye** [comment]
Sounds like you must be using credentials to an account that is not setup with Payments Pro.  

It's possible that you're setup with PayPal Advanced, which uses PayFlow, but would not give you access to the Pro APIs.

Can you verify that you have the full Payments Pro enabled in the account you're working with?

**Comment by muddassirh** [comment]
Here you go please see below from my client account

PayPal Payments Advanced 	Live
Hosted Checkout Pages 	Live 	Test
Payflow SDK/API (Limited Access) 	Live 	--
ACH Services 	-- 	--
Paypal Express Checkout 	Live 	--

Is there anything you can do for me. I am still getting error.

**Comment by angelleye** [comment]
Your account is setup for Payments Advanced, or what is sometimes called Pro Hosted.  This is different from Payments Pro.

Our plugin does support Payments Advanced, so if you want to set that up instead of Pro that would work for you.

Otherwise, you'll need to call PayPal and let them know you want "Payments Pro" instead of "Payments Advanced".
