### ISSUE TITLE
If product is already in the cart and customer hits the Paypal express button on a product page...

### ISSUE THREAD

**Issue by dougm1966** [angelleye/paypal-woocommerce#601]
it refreshes the page.

If a customer adds something to the cart and then decides they don't want to view the cart but actually enter the quantity again and hit the PPexpress button it simply refreshes the page and the customer is confused. It should add the product/or not...and take the customer to the checkout page or accept the new numbers and bypass the cart.

**Comment by dougm1966** [comment]
...or something along those lines. :)

**Comment by angelleye** [comment]
Yes, it should, and we haven't had any other reports of this happening.  Can you try a different theme temporarily to see if the issue goes away?

**Comment by dougm1966** [comment]
I haven't had time to look into this...although I should have...it's cost
me a crap load more money than I originally thought.
This explains and shows double orders and one of them not actually being
paid for.
http://somup.com/cDlnlGdXT

This shows the # of add to carts and # of checkouts...Shocking.
http://somup.com/cDlnQxd6o



ᐧ

Doug Montgomery
ul Orzeszkowej 14/6
Piła, 64-920
tel. 511 008 668

**Comment by angelleye** [comment]
I'm sorry you are so frustrated, but we have 20k+ active users of our plugin and we do not have any other reports of this happening.

When you first mentioned this, I asked you to try switching themes to see if that solved the problem.  The reason I asked this is because it sounds like you have a jQuery conflict happening, and that sort of thing often happens at the theme level.  Switching to a basic theme would confirm that one way or the other.

If it's not the theme, the next step would be to check for a conflicting plugin.  This involves temporarily disabling other plugins and testing a checkout.  If things work, re-enable the plugins one-by-one until the problem comes back to find the culprit.

Once you find the culprit we can try to reproduce on our side and see if there's something we need to adjust in our plugin, something the other plugin developers need to adjust, or maybe even both.

The first step, though, is finding the conflict.  

On a separate note, looking at your video I'm a little confused by something I'm seeing.  At the top of your order screens you just have a label like this for the payment type...

![image](https://cloud.githubusercontent.com/assets/629241/20861680/b9b326ba-b95b-11e6-8026-247d15c8a9b3.png)

Our plugin adds more details than that there, though.  Like this...

![image](https://cloud.githubusercontent.com/assets/629241/20861683/cab73384-b95b-11e6-9d33-413f21599cdd.png)

Even if the order was failing for some reason and there was no transaction ID we should still see empty ()'s and a date / time showing up there.  

This makes me wonder if you are in fact using our plugin for Express Checkout..??  Sometimes people are using the Woo provided Express Checkout plugin and they don't realize I'm not them.  

If you are using our plugin then I'm happy to help you figure out what's going on here, but I need you to follow the steps I outlined above in order to do that.

**Comment by dougm1966** [comment]
Hi Andrew,

My apology's for not testing with a default theme. I just haven't had the
time. I've actually gone into a catalog mode for next week as we are closed
while I'm out of town.

Yes, I'm using your plugin and it appears, from what you're saying, I've
got another issue because what you pointed out, and I'm guessing it's a
plugin conflict...I just don't know how to nail down the error without
deactivating 30+ plugins one at a time.

I've also had some other issues with getting the proper line items sent to
Paypal. When I run a discount using my discount program...the rounding is
an issue for PP. I just deactivated that portion for the time being.

Happy to give you login details if you'd like.

Doug





ᐧ

Doug Montgomery
ul Orzeszkowej 14/6
Piła, 64-920
tel. 511 008 668

**Comment by angelleye** [comment]
Hi Doug,

30+ plugins is the first thing I would try to solve.  That's a lot of plugins to be running and keep maintained without causing conflicts.  Generally speaking in WordPress, the fewer plugins the better.

The best thing to do in this sort of a situation is setup a staging copy of your site at a URL separate from your live site.  This should mirror your live site in every way, but it would be configured to run from that test URL.  Your host can probably help you set something like this up if you don't already have it.

Once that is setup I would get on there and disable everything except for WC and our plugin.  Make sure it works well with limited interference.  Then you can start activating other things one-at-a-time until you see the problem come back.

With that many plugins, too, the odds are you could have more than one conflict, so even if you find one that conflicts after just the 5th try, for example, I would still go the rest as well.

Of course, make sure all your plugins are up-to-date.  If any are still out of date in any way I would start by checking those for conflicts.

**Comment by dougm1966** [comment]
Andrew,

Thank you for your detailed explanation and your detailed response is. It
is very much appreciated.

As for having 30-plus plugins installed, I completely understand what
you're saying about conflicts. Been doing this for about 10 years.
Unfortunately I haven't figured out how to replace plugins with the
functionality they provide in other ways. Of course I would like to have
multiple functions come from one Plugin or as many functions possible come
from one plugin, but sometimes that's not possible.

Over this next week while I'm out of town and our website is closed, I will
be experimenting and playing with this and doing the things you've
recommended. When I get things narrowed down a little bit more and have
some more specific details for you on what's actually happening and when I
figure out conflicts etc, I'll be in touch.

Thank you again for the 300 responses and replies. Something you don't
generally get from a free plugin. I appreciate it.

Doug

**Comment by kcppdevelopers** [comment]
It would be great to provide website URL for find issue very quickly.

**Comment by angelleye** [comment]
@dougm1966 What is your site URL?

**Comment by angelleye** [comment]
@dougm1966 Just wanted to follow up on this again.  Did you get this worked out?

**Comment by angelleye** [comment]
@dougm1966 Never did hear back on this.  Just wanted to check in once more.  Are you still having issues?
