### ISSUE TITLE
Express checkout lets you checkout without a shipping method

### ISSUE THREAD

**Issue by shawaj** [angelleye/paypal-woocommerce#677]
The PayPal express checkout allows you to proceed from the cart/checkout page without a shipping method assigned.

This should not be possible

**Comment by angelleye** [comment]
With Express Checkout the shipping / sales tax details would show up on the review page after the user returns back from PayPal.  This is because there is no address selected until they log in and pick on (unless they're going through your WC checkout page.)

So the standard procedure with EC is that they are able to skip the checkout page, so they don't have to fill anything in.  They log in to PayPal, choose their address, and are sent back to the site where they would then see their shipping / tax options.

Please try that flow and let me know if you still have issues.

**Comment by shawaj** [comment]
No I think you're missing the point of what I was trying to explain.
Probably I didn't explain it well.

Basically, let's say you have a product which you accidentally haven't
assigned a shipping class to - in normal checkout flow, you would not be
able to check out with an item like this in the cart and it would simply
display "no shipping options available".

With express checkout, it lets you checkout all the way through to the end
without a shipping method meaning the customer gets free shipping
effectively... This is wrong.

Thanks,
Aaron

**Comment by angelleye** [comment]
Technically, you should be seeing the "no shipping options available" message on the review page.  Are you saying the review page is displaying, but simply not showing that and allowing them to continue?  Are is your review page not showing up at all (which would mean you must have Skip Final Review enabled in the settings)?

**Comment by shawaj** [comment]
The review page is showing, just let's them finalise the order without a
shipping method.

Which surely isn't correct regardless of whether the "skip final review" is
selected as they still shouldn't be able to complete the order without any
shipping method?

Thanks

**Comment by angelleye** [comment]
Well, people who don't require shipping often like to skip the final review, so that's why the option is there.  If that's not enabled it should be requiring them to choose shipping options on that review page. 

We will take a look at why it's letting you get through in the instance you explained, though, and make any necessary adjustments.  We'll have to move this to the 1.4.3 update because I can't delay 1.4.2 any longer than it's already been delayed, but we'll get it done ASAP!

**Comment by shawaj** [comment]
Thanks very much. It's a niche case I guess, in that the product in question should have had a shipping method assigned.

But I think it's better to not let someone check out in this scenario than to let them checkout with no shipping option and have us loose money.

**Comment by angelleye** [comment]
Yup, I agree.  We'll see what we can do about that.

**Comment by shawaj** [comment]
Thanks, and thanks for an awesome plugin.

It's great to see someone developing a really great PayPal plugin.... WooCommerce and automattic don't seem capable.

**Comment by angelleye** [comment]
Thanks for the feedback!  We're in a bit of a rut with this 1.4.x update and all of the changes WC 3.0 made, but we're working it out and then we'll be back to normal again.  :)
