### ISSUE TITLE
Fatal error updating from 1.3.2 to 1.4.2..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#693]
* https://www.angelleye.com/forum/discussion/comment/789

**Comment by MansoorAliKhanOfficial** [comment]
HI @angelleye I tried to install 1.3.2 first then , using normal update from plugins, updated it to latest version and not issue found, the issue seems like a server side issue which shows 500 internal server error. may be he is using someother plugins which might be using the same function which might be conflicting.

need to check on client site specifically. right @kcppdevelopers ??

**Comment by kcppdevelopers** [comment]
#697
