### ISSUE TITLE
Payment gateways  not showing on checkout page

### ISSUE THREAD

**Issue by MansoorAliKhanOfficial** [angelleye/paypal-woocommerce#696]
HI 

Can you please review these screenshots, I have enabled and configured almost all payment gateways but only these 2 showing as highlighted in the screen show.
can you tell what could be the possible issue? what I m missing in configs, any specific requirements for them to show?

Theme Flatsome

![img_05052017_192257_0](https://cloud.githubusercontent.com/assets/11312949/25769734/dbf0f330-323a-11e7-9ff5-3bfd9ea0acd0.png)

![img_05052017_192257_1](https://cloud.githubusercontent.com/assets/11312949/25769735/e3c7320e-323a-11e7-8e8d-fea14d2584b5.png)

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial All the Payment gateway display on the checkout page not on checkout page.

You have provided screenshot is cart page, please check checkout page and let me know if not working on the checkout page.

**Comment by MansoorAliKhanOfficial** [comment]
@kcppdevelopers let me check,

Just to ask aren't they supposed to show on this page just like ppal for woo EC buttons and pay credit?

**Comment by kcppdevelopers** [comment]
@MansoorAliKhanOfficial  we are only display express checkout PayPal and credit card button on cart button.

**Comment by angelleye** [comment]
@MansoorAliKhanOfficial What you said is correct.  Most of the plugin gateways are only meant to be displayed as options on the WooCommerce Checkout page and would be included in the regular list of gateways that comes with WooCommerce.

PayPal Express Checkout is slightly different because it offers the ability to click a single button and checkout form anywhere.  As such, we've included the ability to utilize this functionality from the product pages, the cart page, etc.  This feature alone is what causes the conversion rates on websites to increate by around 25% when Express Checkout is added to a site.

Closing this issue, but let me know if you have any questions about any of this.

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
Can you please review these screenshots, I have enabled and configured almost all payment gateways Paypal , Alpha Bank but only Direct payment and paypal shown in checkout page but not Alpha Bank. i am unable to pay with bank so, 
can you tell what could be the possible issue? 

![git2](https://user-images.githubusercontent.com/25637572/32886228-22f780c8-cae8-11e7-9a7b-a4b0a4b93b3b.png)

![git](https://user-images.githubusercontent.com/25637572/32886243-2da89462-cae8-11e7-8a4b-744d373b01a1.png)

Regards: Pankaj Adhikari

**Comment by angelleye** [comment]
From the look of this screenshot you don't have our plugin installed/active.  We can't support issues you're having with other gateways.

**Comment by RSAAUTHENTICATIONPANKAJ** [comment]
how to fixed it ,if possible please recommenced me any bank gateway system in git hub

**Comment by engrmostafijur** [comment]
GoEmerchant  is not showing in my checkout page .. Pleas help me !!!!!!!!!!!!! 

https://www.vocalboothtogo.com/checkout/  I cann't find good solution help me !!!!!!!!!!

**Comment by engrmostafijur** [comment]
![image](https://user-images.githubusercontent.com/7710230/33087720-971a5d78-cf15-11e7-9101-bbc6f68b3b88.png)

**Comment by engrmostafijur** [comment]
Please help me !!!!!!!!!!!

**Comment by angelleye** [comment]
@engrmostafijur I'm sorry for the delay responding.  This issue was closed, so it wasn't popping up on my priority list.  Are you still having problems at this point?  If so I need you to clarify exactly what issue you are having please.  You mentioned GoEmerchant, but that would have nothing to do with us, so I'm a little confused.
