### ISSUE TITLE
Express Checkout - Addresses are not passing around correctly..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#742]
* https://wordpress.org/support/topic/billing-details-as-shipping-details/
Ticket: https://www.angelleye.com/support/scp/tickets.php?id=1217

>Let explain in more detail… If I am shipping an order to my parents (for example) I enter my info in PayPal’s billing portion of the form and then enter my parent’s info in the shipping portion of the form. It all passes in PayPal, but when comes back to my site, the billing details has my name but my parent’s address. And sometimes it fills the ship form with the shipping info from PayPal and sometimes it does not – even when I use the exact same information in the testing.

>I have “Billing Address” in the settings unchecked.
I also cleared the WC Transients, Expired transients, Customer sessions.

**Comment by angelleye** [comment]
Re-opening this because the user in the thread above says he applied the update, and things changed, but still aren't correct:

>I have just updated the plugin and I am still getting the same results – or close to similar. Now the billing portion of the confirmation page is always the shipping address from Paypal and the shipping form in the confirmation page is always blank. I have tried it with the “Billing Address” in the settings checked and unchecked. Can it be something in the settings that I am missing?

**Comment by kcppdevelopers** [comment]
@angelleye  I have tested with all the possible cases and it's seems working fine for me.

**Comment by SimetriaStudio** [comment]
Hi @kcppdevelopers @angelleye I was the person that brought up this particular case initially. I am still experiencing this phenomenon. I'm still experiencing this issue. After I fill out the Paypal form and select a different shipping address from the billing address, when I come back to the confirmation page, the billing address is set to PayPal's shipping address and the shipping form (in confirmation page) is blank - on occasions it pre-fills, but most times is empty. Would giving you guys admin access to the site give you a better view on what's happening and/or the issue?

**Comment by kcppdevelopers** [comment]
Hello @SimetriaStudio I have checked your website and found that In the setting panel you have enable PayPal Account Optional and Landing Page = Billing, when customer click on PayPal button on cart or checkout page it will redirect to https://www.screencast.com/t/Ytf7VrUT right? Then User fill-up  both shipping and billing address. PayPal express checkout return only shipping address and our express checkout payment will display on billing section on order review page. still customer have option 'SHIP TO A DIFFERENT ADDRESS?' if user fill-up different address then our plugin used different address as shipping address otherwise used as billing address which return from PayPal.  I think our plugin working as per WooCommerce default checkout page behavior.  Please correct me if I am wrong.

**Comment by SimetriaStudio** [comment]
That's correct. Because of the nature of our business, we almost never get an order where the shipping address is the same as the billing address. AND 90%+ of our customers want to pay with their credit card. 

So, if I'm customer and I made my way to the PayPal page and fill out all of my billing information, and then fill out the information to whom I will be shipping to (still in the PayPal form), then I get redirected to the confirmation page and I see that the billing address is showing the shipping info and I have to re-type all the shipping information on the confirmation page again, I'm going to get upset and complain about it. It's just inconvenient. Also prior to the last major update from woocommerce and every other plugin dependant on woocommerce, this setup was working perfectly. It would return the shipping address and prefill the form in confirmation page, and would not show billing address as shipping address.

**Comment by angelleye** [comment]
@SimetriaStudio What @kcppdevelopers said about PayPal only returning a shipping address is correct.  So one way or another we only have that address to work with.

That said, it should be populating anywhere that shipping is stored/displayed, but I'm a little confused about the additional shipping form you are mentioning on the confirmation page..??  Typically by that point the address is already set and there is no form to enter.  It would just display the address that was chosen and provide any shipping calculation options based on that address.  

Can you provide screenshots or a demo video of the experience you are having?  I think will help clear some things up for us.

**Comment by angelleye** [comment]
@SimetriaStudio Nevermind, I see what you're referring to now.  Discussing it with @kcppdevelopers.  I agree it's not ideal so we'll figure something out here.

**Comment by angelleye** [comment]
@SimetriaStudio Our 1.4.0 update revamped the way Express Checkout is built into WooCommerce.  We used to have a completely custom review page that worked how I mentioned above.  Now we're using the built in WooCommerce templates for the review page, and we overlooked how it sort of fights the flow of Express Checkout the way you explained.  We're going to customize the page template so that it simply displays the existing billing/shipping at that point without any option to "ship to a different address".  The billing side will simply display the name and email address of the payer, and the shipping side will display the address returned by PayPal at that point.  We're working on that now and we'll have update for you before long.

**Comment by SimetriaStudio** [comment]
@angelleye @kcppdevelopers Yes that would be perfect. At that point in the purchasing process (confirmation page) there should NOT be any more forms to fill out, just a quick overview of all the information inputted in PayPal just to check for any errors/typos. 
Thanks Guys.

**Comment by angelleye** [comment]
@SimetriaStudio We have made adjustments that should take care of this.  If you'd like to [download the release branch](https://github.com/angelleye/paypal-woocommerce/archive/release.zip) and give it a shot we'd appreciate any feedback you can provide.  Thanks!

**Comment by SimetriaStudio** [comment]
@angelleye Thank you. I will be downloading and testing soon. I will let you guys know if I see anything. Thanks again gentlemen.
