### ISSUE TITLE
Express Checkout - Guests unable to proceed to checkout..??

### ISSUE THREAD

**Issue by angelleye** [angelleye/paypal-woocommerce#744]
* https://wordpress.org/support/topic/guests-unable-to-procced-to-checkout-paypal-express-redirect-back-to-cart/

>Since your last update 6 days ago, we had to deactivate your plugin, due to the following issues

>1) Guests can’t checkout using “paypal express” they gets redirected back to cart
>2) Logged in users can checkout and it works as expected.

>We confirmed API user, password and signature, nothing in the debug logs that would shed light on this issue.

**Comment by kcppdevelopers** [comment]
@angelleye 

1) WordPress Support: https://wordpress.org/support/topic/guests-unable-to-procced-to-checkout-paypal-express-redirect-back-to-cart/

2) https://wordpress.org/support/topic/paypal-express-checkout-page-missing-member-login-form/#post-9145066

In the 1) issue they said “Guests” Unable to proceed to checkout PayPal Express- redirect back to cart
and 2) issue they given reply 'login not working on review page'. then it seems to proceed to checkout PayPal Express already working well, otherwise how they get review page without login.

**Comment by angelleye** [comment]
I responded to the user asking if they can update to our latest release branch and see if they're still having issues since the second issue is closed in the release branch.
