### ISSUE TITLE
Paypal express checkout - Call to undefined method WC_Checkout::is_registration_required()

### ISSUE THREAD

**Issue by njbarrett** [angelleye/paypal-woocommerce#926]
Call to undefined method WC_Checkout::is_registration_required()' in /wp-content/plugins/paypal-for-woocommerce/classes/wc-gateway-paypal-express-angelleye.php:936

We're using Woocommerce 2.6.13 which appears to be a supported version of the plugin.

It seems it is trying to access a function that isn't available in this version of Woocommerce.

I think this code needs a compatibility check for < Woocommerce 3.0

**Comment by angelleye** [comment]
Thanks for the feedback.  Actually, we have listed 3.0 as the minimum required WC version at this point, and we added that to the plugin comments per the WooCommerce version tracking functionality they recently added.

```
 * WC requires at least: 3.0.0
 * WC tested up to: 3.2.2
```

I guess if you're still running an old version that really isn't doing anything for you.  Where did you see we have it listed for 2.6 support?  I need to get that adjusted.  

I would recommend you get updated.  If you're stuck in an old version because of theme or plugin customization that was done improperly then you'll need to get that fixed so you can get updated sooner rather than later.  This sort of thing will only become a bigger problem the longer you wait.

**Comment by njbarrett** [comment]
@angelleye Thanks for the prompt response.

The readme.txt lists the requirements as:

**Requirements**
PHP version 5.3+.
WordPress 3.8+
WooCommerce 2.3+

Do you happen to know the last version to support WC 2.6 ?

**Comment by angelleye** [comment]
I would try our version 1.3.3 and see if that works better for you.  You can download previous versions here:  https://wordpress.org/plugins/paypal-for-woocommerce/advanced/

**Comment by njbarrett** [comment]
@angelleye Thanks for that.
Just noticed another location which needs the minimum requirements updated:
https://www.angelleye.com/paypal-woocommerce-installation-guide/ Under minimum requirements.

**Comment by angelleye** [comment]
Thanks, I got that updated.
