### ISSUE TITLE
Continued rounding errors

### ISSUE THREAD

**Issue by robwatson-intechra** [angelleye/paypal-woocommerce#987]
In reference to #892, #909, and #908, we are still experiencing order amount rounding issues that are causing us to have to pay change fees to our fulfillment company for each order that has this problem. This time I'm attaching a series of recent orders (with sensitive customer data obfuscated) in case a larger pattern can be revealed that might lead to a fix. Included at the bottom of the document is our WooCommerce status and config.
[orders-with-rounding-errors.txt](https://github.com/angelleye/paypal-woocommerce/files/1664302/orders-with-rounding-errors.txt)

**Comment by angelleye** [comment]
Interesting.  The math actually does add up in these cases, and it does show Approved with the warning about the item amount being invalid.  Are you seeing these payments show up in your PayPal account, or are they declining altogether?

I see an item with QTY 3 at 29.67, which is a total of 89.01.  Then it's subtracting the penny as a line item discount to make the subtotal 89.00, which is indeed what is getting set for the ITEMAMT and the AMT, so it does add up and really shouldn't be throwing this error.  I may need to circle back to PayPal MTS on this particular example.

Are you using 3 decimals in your pricing or something unique like that, by chance?  It's odd that if the line item details are coming to 89.01 that WooCommerce would be calculating an order total of 89.00 even.  Our system is then subtracting the penny so that the subtotal/itemamt matches the line item totals.  So again, it's strange that it's telling us the itemamt is invalid when it's not.  

Do you have any idea why WC would be calculating an order total of 89.00 even when you've got 3 items at 29.67 in the cart?  We're just pulling what the WC cart object returns, so we need to figure out what's going on there.

**Comment by robwatson-intechra** [comment]
The products are selling and being shipped, so they are definitely going into PayPal as completed orders. I'd have to individually confirm the exact amounts in PayPal, but I don't have access to that at the moment. I'll have to get back to you on that. What I do know is that the amounts arriving at the fulfillment center are off by varying penny amounts and those are having to be corrected, with us getting charged back for their time in doing so.

We are using a [dynamic pricing plugin](https://woocommerce.com/products/dynamic-pricing/) for calculating bulk pricing. For the majority of our sales of a particular product (which this batch of orders mostly consists of), the quantities purchased don't reach the level that includes even one decimal in the price multiplier factor. Only one of these orders reaches that level of quantity. These orders were mostly calculated using whole numbers or one decimal place for multipliers and just two decimal places for prices.

The reason it calculates to 89.00 with 3 items @ 29.67 is because 3 * 29.67 = 89.01, but the subtracted penny is what we want to figure out. Put another way, 89.00 / 3 = 29.66666666666667. So, the rounding of that price is the problem, in my understanding.

Here's a screenshot of the discount scale applied for that product. Regular price is $34.00 and it gets discounted the more you buy.

![pricing-group](https://user-images.githubusercontent.com/24557637/35456248-d2fd2f94-02a2-11e8-9e4d-ce122e083ea5.png)

If you need direct access to the website, I can provide it. Just email me at rwatson at intechrahealth.com.

Also, what about those orders that are Approved but the IP address is invalid? Why would those have had off-amounts that would trigger the changes at fulfillment?

**Comment by angelleye** [comment]
Thanks again for the details.  I've got this added to our 1.5.0 milestone, so we'll just need to see if we can reproduce the problem using that dynamic pricing plugin and make necessary adjustments to resolve it.  

I'm not sure what you're referring to about approved orders with invalid IP address..??

**Comment by crobertwatson** [comment]
Thanks. As for the ones that had error messages saying the IP address is invalid, they also got flagged by our fulfillment as being out of balance on the amounts. Do you see the same? Maybe I need to have a conversation with them about those, if not.

**Comment by angelleye** [comment]
Is the IP address error coming back from PayPal, or where exactly are you seeing that?  I'm just not clear where that's coming from..??

**Comment by robwatson-intechra** [comment]
The IP address error is coming back from PayPal from what I can tell in the log file.

**Comment by angelleye** [comment]
Are you using the latest version of our plugin?  There were some IP address issues that stem from some servers returning the IPv6 value, but PayPal only accepts IPv4.  We made adjustments to this in our latest updates and other than this report we haven't had any other reports of that problem since then.  Please verify you're using the latest version of our plugin..??

**Comment by robwatson-intechra** [comment]
We're using Version 1.4.7.2.

**Comment by angelleye** [comment]
So which gateway specifically is this happening with?

**Comment by robwatson-intechra** [comment]
Payflow. These are showing up in the Payflow logs in WooCommerce > Status > Logs > paypal_pro_payflow....log

**Comment by angelleye** [comment]
@robwatson-intechra We've made some adjustments here that should resolve this, and I'll be pushing a 1.4.7.3 update soon.

**Comment by angelleye** [comment]
No problem at all, we appreciate the feedback!

**Comment by robwatson-intechra** [comment]
Now that we've updated to this version (actually version 1.4.7.4 now), we caught these two "out of balance" items. The error messages from the fulfillment vendor are as follows:

Message: Order: 218731 Error: orderTotal of 92.00 is not equal to the sum of line item, shipping, tax and discount applied charges of 92.0100 (Order.orderTotal)

Message: Order: 218725 Error: orderTotal of 179.00 is not equal to the sum of line item, shipping, tax and discount applied charges of 178.9800 (Order.orderTotal)

Attached is the WC PayFlow log of these two orders.
[payflow-orders-log.txt](https://github.com/angelleye/paypal-woocommerce/files/1729852/payflow-orders-log.txt)

If you need access to the live system, I can provide the login information via private email.

**Comment by robwatson-intechra** [comment]
Here are the pricings for the order for 92.00 (which is the total for quantity = 3 of this particular product). Is it that we have too many or too few decimal places?
![pricing-group](https://user-images.githubusercontent.com/24557637/36321389-b918ce96-1317-11e8-8ac9-d23fb108eb04.png)
![regular-pricing](https://user-images.githubusercontent.com/24557637/36321390-b925c272-1317-11e8-8093-1b0a3de2cc5f.png)
